### ISSUE TITLE
Lauds and Vespers bug

### ISSUE THREAD

**Issue by filleduciel** [HackMyChurch/aelf-dailyreadings#1]
Hello,
 
I downloaded the AELF application.
There are apparently two bug that makes it unusable with respect to the website:
- it lacks the hymns in Lauds
- it lacks the word of God in Vespers
There he expected a correction?
if not, how to correct (I'm a computer scientist but I never developed in java android)?

**Comment by yadutaf** [comment]
Hello !

Merci pour votre retour ! Je suis ravi que vous souhaitiez contribuer. N'hésitez pas si vous avez besoin d'aide. Les textes viennent du site AELF via leurs flux rss. L'application les télécharge et les mets en forme.

Concernant les lectures manquantes, j'ai pris contact avec AELF. Je vous tiendrai au courant.

**Comment by yadutaf** [comment]
Bonne nouvelle, la lecture est de retour dans les vêpres. Les autres soucis seront réglés avec les contournements mis en place dans la prochaine version. Merci pour votre retour !

**Comment by filleduciel** [comment]
Bonjour,

Je viens de refaire une vérification par rapport au site AELF : toutes des erreurs ont été corrigées.
C'est super l'appli est vraiment utilisable.
juste une remarque :
la correction n'apparait que sur les nouveaux jour chargés : exemple si je regarde des vêpres d'aujourd'hui l'erreur y est encore et n'est pas corrigé par l'entrée du menu "synchroniser" qui est sans action et qui ne recharge pas des jours déjà chargés. c'est pas un problème majeur.
dans mon cas particulier j'avais configurée l'appli avec un chargement 1 mois à l'avance, j'ai donc encore l'erreur pendant un mois ce qui est un peu génant dans cette phase pas encore stable
pour y remédier il pourait etre envisagé une fonction suplémentaire de forcage de synchronisation qui recharge tous selon la configuration meme les jours déjà chargés.

quels sont "les autres soucis" que vous pensez régler "par des contournements" dans la prochaine version ?


Cordialement,

Geneviève ALBERGNE

2300 av Auguste Mavy
13480 Cabriès
Tel : 04.42.51.00.21
       06.66.32.19.15

  ----- Original Message -----

**Comment by yadutaf** [comment]
> la correction n'apparait que sur les nouveaux jour chargés : exemple si je regarde des vêpres d'aujourd'hui l'erreur y est encore et n'est pas corrigé par l'entrée du menu "synchroniser" qui est sans action et qui ne recharge pas des jours déjà chargés

Vous pouvez "raffraichir" ou reinstaller l'application pour provoquer un rechargement (ou attendre la prochaine version qui effacera le cache)

> quels sont "les autres soucis" que vous pensez régler "par des contournements" dans la prochaine version ?

- ajout du "Notre Père" dans les vêpres
- ajout du "Bénédiction" dans les complies
- (peut être) ajout du verset à la fin de la psalmaudie de l'office des lectures
