### ISSUE TITLE
Move theme switcher button

### ISSUE THREAD

**Issue by nathanael-h** [HackMyChurch/aelf-dailyreadings#11]
J'ouvre cette issue à la suite de https://github.com/HackMyChurch/aelf-dailyreadings/pull/9#issuecomment-433647784

@nath5394 
> Enfin, je pensais à une autre amélioration pas directement liée : rendre le switch du thème plus accesible, par exemple dans le menu de droite. (On peut suivre ça dans 2 autres issues si tu souhaites).

---

@yadutaf 
> Au sujet du "switch plus accessible", je serais intéressé par une contribution. Je ne sais pas s'il sera facile de l'intégrer dans le menu à droite. Le cas échéant, une option alternative serait de le placer dans le menu latéral. La modification ne devrait pas être très compliquée. Tu prends le sujet ?

---

Je vais regarder ce sujet. ça me parait même mieux de le mettre dans le drawer.

**Comment by yadutaf** [comment]
Le bouton est maintenant dans le menu en haut à droite. Il me semble que cela répond au besoin :)
