### ISSUE TITLE
P'tit encouragement en passant...

### ISSUE THREAD

**Issue by Scriptura** [HackMyChurch/aelf-dailyreadings#3]
Bonjour a vous Jean-Tiare (alias YaDuTaf/CathoGeek),

J'allais rédiger une issue pour vous signaler que des versets avaient disparus dans le Cantique Ex 15 de la Veillée Pascale, mais en fait non : après vérification il s'agit d'un choix de l'AELF dans la coupure des textes pour les dernières éditions postérieures à deux ans...

Quoi qu'il en soit je tenais tout de même à rédiger ce message pour (re)saluer votre énorme travail sur l'application "Aelf - Lectures du jour", pour moi de loin la meilleure sur le store.

Longue vie à l'appli ! (et accessoirement à son auteur :wink:)

**Comment by yadutaf** [comment]
Merci ! En effet, que d'alias :)

Seriez-vous prêt à me prêter main forte ? Il y a du Python, du Java et... de l'UX (no code required)

**Comment by Scriptura** [comment]
Oui, j'ai vu tout ça en parcourant votre code mais, hélas, je ne pense pas pouvoir vous être utile.

N'étant présent sur le web qu'en amateur et formaté aux environnements LAMP, je passe (très) progressivement sous Node.js (pour l'intérêt du truc). Mais désormais je manque de temps pour m'investir sur d'autres technos...

Quand à l'UX, quand on vois l'appli telle qu'elle est actuellement, honnêtement, je trouve que vous vous en sortez très bien. Certes "on peut toujours faire mieux" mais là, tout de suite, je ne vois pas, en tout cas pas assez loin...

**Comment by Scriptura** [comment]
Petit coucou en passant,

Déjà deux ans que j'utilise l'appli quotidiennement : parfois un bug de chargement (rare) mais sinon que du bonheur. Un must have pour moi.

Pour la présentation de l'app, je ne voyais pas ce qui pouvais être amélioré, mais depuis l'apparition du mode "nuit" sur une MAJ je n'utilise plus que lui : anti distraction par excellence, surtout en interrieur (en particulier dans une église). Le top.
