### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by ildar** [HackMyChurch/aelf-dailyreadings#36]
Greetings!
I'm not sure if developers want it, but: is it desirable/possible to elaborate International English interface?
Thank you.

**Comment by nathanael-h** [comment]
Hello, this would be a very nice feature to provide a multilingual app. In the project I am working actually, I can tell you that it is a long term feature I target. Find it here : https://gitlab.com/nathanael2/aelf-flutter 

For the actual AELF project It would be to difficult for me to add this feature, and I think @yadutaf  does not have enough time for now. 

Would you like to work on this feature ? Here or on this project or the other I mentioned ?

**Comment by yadutaf** [comment]
AELF is the French not-for-profit providing the official Catholic church French translation of the Bible. Providing an English translation is not part of its missions.
