### ISSUE TITLE
debug version build

### ISSUE THREAD

**Issue by gspeiliu** [HackMyChurch/aelf-dailyreadings#39]
Hello, I want to build the project on my own and I execute the build command provided by Gradle.

./gradlew assembleDebug
* What went wrong:
Execution failed for task ':sqlite3:generateJsonModelDebug'.
> Build command failed.
  Error while executing process /home/xxxxxx/Android/Sdk/ndk/20.0.5594570/ndk-build with arguments {NDK_PROJECT_PATH=
null APP_BUILD_SCRIPT=/home/xxxxxx/Downloads/BuildSystem/Repos/HackMyChurch#aelf-dailyreadings/sqlite3/src/main/jni/$
ndroid.mk NDK_APPLICATION_MK=/home/xxxxxx/Downloads/BuildSystem/Repos/HackMyChurch#aelf-dailyreadings/sqlite3/src/ma$
n/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/home/$
eiliu/Downloads/BuildSystem/Repos/HackMyChurch#aelf-dailyreadings/sqlite3/build/intermediates/ndkBuild/debug/obj NDK$
LIBS_OUT=/home/xxxxxx/Downloads/BuildSystem/Repos/HackMyChurch#aelf-dailyreadings/sqlite3/build/intermediates/ndkBui$
d/debug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

  /home/xxxxxx/Android/Sdk/ndk/20.0.5594570/build/core/gdb.mk:33: *** missing separator.  Stop.

OS: Ubuntu 18.04 LTS with latest Android Studio.

Could you please tell me how can I build the project and what should I do to fix the build problems?
Thanks

**Comment by yadutaf** [comment]
No clue :) I'm building from Ubuntu 20.04 on my side, using Android Studio (no direct command line call)
