### ISSUE TITLE
Add full Bible

### ISSUE THREAD

**Issue by nath5394** [HackMyChurch/aelf-dailyreadings#4]
Bonjour, 
Est-il prévu d'ajouter la Bible avec un accès hors ligne ? 
Si non, on ferme l'issue ici, et on continue à discuter par email ou autre ;-) 
Si oui, super !!
Poke @amdg2

**Comment by nath5394** [comment]
et le lien http://services.aelf.org/ aussi 😞

**Comment by yadutaf** [comment]
Alors, oui, j'en rêve. Mais soyons réalisé, je n'ai plus le temps :/ En revanche, ce serait une joie d'aider quelqu'un à le faire !

**Comment by AMDG2** [comment]
Moi j'ai une question pour @yadutaf qui a de l'expérience avec l'AELF. Penses-tu que c'est plus simple légalement d'intégrer leur traduction de la bible dans l'appli existante ou dans une dans une nouvelle appli ou les deux te paraissent aussi compliqué ?

Sinon @nath5394 est super motivé, il a déjà un truc fonctionnel à base de Webview et d'une version hors-ligne. 

Le 6 novembre 2017 22:14:16 GMT+01:00, Jean-Tiare Le Bigot <notifications@github.com> a écrit :
>Alors, oui, j'en rêve. Mais soyons réalisé, je n'ai plus le temps :/ En
>revanche, ce serait une joie d'aider quelqu'un à le faire !
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/HackMyChurch/aelf-dailyreadings/issues/4#issuecomment-342288809

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by yadutaf** [comment]
Top pour la version qui fonctionne ! Tu as une démo ? Pour proposer la Bible sous forme d'une application dédiée ou dans l'application qui existe, c'est comme tu veux. Bien sûr, j'ai une préférence pour l'application existente ;) Cela permettrait de faire un lien entre les offices et la Bible pour afficher les textes dans leur contexte. Et ça, ce serait top.

Quelque soit l'option, je pourrais vous donner un coup de main, y compris en vous mettant en lien avec AELF.

Bonne soirée

**Comment by nath5394** [comment]
Salut, mon projet à base de webview est sur gitlab dans un dépôt privé, car pas de dépôt privé gratuit chez github. Si vous voulez crééez-vous des comptes gitlab et je vous donne les accès. 
Je ne veux pas rendre le code public tant que l'AELF n'a pas donné un feu vert, car j'ai dedans toute la Bible.

**Comment by AMDG2** [comment]
https://gitlab.com/amdg2

**Comment by yadutaf** [comment]
https://gitlab.com/yadutaf

**Comment by nath5394** [comment]
Ça y est je commence à essayer d'intégrer la Bible : https://github.com/nath5394/aelf-dailyreadings/tree/add_bible 
(Ah si je savais développer... !!)

**Comment by nath5394** [comment]
Solved by https://github.com/HackMyChurch/aelf-dailyreadings/pull/7
Releases will come as soon as @yadutaf can in Google Play, maybe F-droid, and why not in Github directly.
