### ISSUE TITLE
Onglet de lectures au choix

### ISSUE THREAD

**Issue by Scriptura** [HackMyChurch/aelf-dailyreadings#40]
Bonjour,

Dans la nouvelle version de l'application, pour les onglets de lecture au choix, il peut y avoir un bug qui n'est pas systématique.

Par exemple, en ce jour de la Nativité de la Vierge Marie, l'onglet de lectures au choix pour l'Évangile est correct, mais celui de la première lecture affiche le contenu intégral de la lecture au lieu d'une proposition entre deux choix de lectures.

Merci encore et toujours pour votre application, que j'utilise quotidiennement depuis au moins 2 ans déjà.

**Comment by yadutaf** [comment]
Bonjour,

Auriez-vous une capture d'écran ? Sur ma tablette, je vois les titres les 2 propositions de lectures. C'est un peu verbeux, mais ce n'est pas la lecture complète :)

**Comment by Scriptura** [comment]
Autant pour moi : j'ai interprété le menu comme étant un get du content plutôt que d'un title. Surtout que le menu pour l’Évangile c'est très clair et concis ("lecture longue", "lecture brève").

Du coup je réoriente ma question sur un aspect UX : ne serait-il pas plus judicieux de récupérer autre chose que la phrase d'accroche, du genre "Lecture du livre de Michée" ? Mais c'est à réfléchir là encore car, une fois que l'utilisateur est familiarisé avec l'app, la phrase d'accroche devient plus intérressante que l'annonce d'un chapitre de bible.

PS1 : en mode sombre le menu ne se distingue pas vraiment du fond, contrairement au mode clair.

PS2 : il reste un reliquat de l'ancien mode d'utilisation, la première lecture proposée par défaut se termine par "OU BIEN". Ç'est pas très joli, mais peut-être codé en dur dans le data récupéré ? Un petit regex dessus au pire...

Cordialement

**Comment by yadutaf** [comment]
En effet, les alternatives ne se trouvent pas dans les données sources. Ce que l'on trouve ce sont les "OU BIEN" ou similaire que vous mentionnez. De fait, ces relicats pourraient être filtrées, et ce ne doit pas être insurmontable :) (D'ailleurs, si le Python ne vous fait pas peur, le code du serveur de l'application est dans la même orga ;)).

Pour le titre, je suis ouvert aux suggestions. Quand le texte ne contient que "OU BIEN", j'ai voulu donner une indication claire des alternatives possibles avec les titres. "Option 1", "Option 2" n'étant pas super, super clair...

Pour le menu en ode sombre, je vais regarder si je trouve un peu de temps. Avez-vous des suggestions ? Il me semble que la même couleur est utilisée pour l'ensemble des menus, y compris le le menu des "..."

**Comment by yadutaf** [comment]
J'ai déployé un nouveau serveur "bêta". Les "OU BIEN", "OU LECTURE BREVE" sont supprimés automatiquement.

Une fois sur le serveur "bêta", il suffira de "raffraichir" la lecture pour avoir le changement. Pas besoin de mettre à jour l'application.

**Comment by yadutaf** [comment]
> Du coup je réoriente ma question sur un aspect UX : ne serait-il pas plus judicieux de récupérer autre chose que la phrase d'accroche, du genre "Lecture du livre de Michée" ?

Suggestion appliquée en bêta, quand l'introduction lue (Lecture du ...) est différente entre les propositions de lectures. Merci !

**Comment by yadutaf** [comment]
Et la prochaine version aura une meilleure lisibilité pour le menu dans le mode "nuit"

Résulat avec les 3 changements:

![image](https://user-images.githubusercontent.com/739985/93002150-e3f7e500-f534-11ea-899f-d4c735ed22dc.png)

**Comment by Scriptura** [comment]
Oulà, trois messages ! Pardon de ne pas avoir été réactif...

Pour répondre au premier d'entre eux : je ne connais ni python, ni java, ni le monde des app Android. Ces technos vallent sans doute la peine que l'on s'investisse dedant mais je suis et reste un amateur, qui n'a matériellement pas le temps de taper dans toutes les technos (même si l'envie ne manque pas). Mon environnement désormais - après avoir touché à php - c'est node.js...

Pour le deuxième message, je pense effectivement que les titres ainsi proposés sont plus clairs.

Enfin, pour le dernier message à propos des couleurs, je trouve que le contraste entre la couleur de fond (#131720) et les autres éléments ne reste pas assez tranché, même avec l'entête principale d'ailleurs. Je vous fais une proposition bientôt. Bien sûr ce sera à vous de voir : c'est votre bébé et là on touche à son identité.

**Comment by Scriptura** [comment]
J'ai essayé la bêta, elle est très bien. En fait c'est très bien comme ça, faut rien toucher. Peut-être...

... un petit badding-bottom pour le menu ouvert (égal au padding perçu à sa gauche) ? Ça ferait super propre comme finition.
