### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [HackMyChurch/aelf-dailyreadings#41]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by AMDG2** [comment]
There are screenshots in F-Droid when using french locale. However the images are not present in fastlane data for en-US locale (which is the fallback used by F-Droid)

@yadutaf in `fastlane/metadata/android/en-US` directory we could add symlink to `fastlane/metadata/android/fr/phoneScreenshots`, `fastlane/metadata/android/fr/sevenInchScreenshots` and `fastlane/metadata/android/fr/featureGraphic.jpg`. That way there is only one place where you need to update the screenshots, but they will display stuff in french for everyone (which is ok IMHO as the readings are only in french).

**Comment by mondlicht-und-sterne** [comment]
yes that only works with fastlane

**Comment by yadutaf** [comment]
The symlink option sounds good to me considering this application only makes sense to french speaking people :) Would you agree to submit the change ?

**Comment by mondlicht-und-sterne** [comment]
In case you add screenshots to your fastlane, F-Droid will get them automatically and another team at F-Droid can take care of it, or the next sync will include the pictures.
