### ISSUE TITLE
L'option "Afficher le changement de ton" n'affecte pas les psaumes dans les modes "Messe" et "Bible"

### ISSUE THREAD

**Issue by bandang0** [HackMyChurch/aelf-dailyreadings#43]
Il est impossible d'afficher le changement de ton des psaumes dans les modes "Bible" et "Messe", même avec l'option "Afficher le changement de ton". Est-ce normal?

**Comment by yadutaf** [comment]
Le changement de ton des psaumes n'est pas présent dans les données fournies par AELF dans la Bible et dans la messe. Ces informations ne sont présentes que dans les offices.

Je vous invite à contacter directement AELF pour les données elle-mêmes. https://www.aelf.org/contact

**Comment by bandang0** [comment]
@yadutaf Ah d'accord, je vois qu'il en est de même sur aelf.org. Il y a-t-il moyen pour vous d'avoir les versions avec changement de ton de tous les psaumes à l'avance et les afficher dans Messe et Bible?

Merci

**Comment by yadutaf** [comment]
Si AELF apporte le changement, cela sera automatiquement répercuté dans la messe. Pour la partie Bible, il faudra préparer une mise à jour, mais ce n'est pas très compliqué à faire :)
