### ISSUE TITLE
403 on every service / reading starting from today

### ISSUE THREAD

**Issue by etiennecallies** [HackMyChurch/aelf-dailyreadings#44]
Hi, I have been using AELF android app and so has my wife, for years (thank you very much by the way).

We both got this error this morning, and for any future date. I'm using the latest version 2.7.5. Is it because of the new liturgical year?
![Screenshot_20211126-092905_AELF](https://user-images.githubusercontent.com/7634514/143590761-84ecc813-a257-4690-813d-d95788a98981.jpg)

**Comment by yadutaf** [comment]
Hi,

There indeed was an issue on the server side. It was solved early this 
morning. The proper readings should eventually reach your phones later 
today (the server side load is a bit high at the moment, while the fix 
is propagating). Sorry for the inconvenience

**Comment by etiennecallies** [comment]
I cleared the app data, and now it works perfectly. (I could have tried to simply sync or refresh though). Many thanks :)

**Comment by fabflop** [comment]
@etiennecallies I had the same problem. Thanks to your posting, I was able to resolve it by refreshing. Merci beaucoup for posting it!
