### ISSUE TITLE
Add support for themed icons

### ISSUE THREAD

**Issue by ascpial** [HackMyChurch/aelf-dailyreadings#47]
With android 13 comes the ability for apps to set a monochrome icon that will be synced with the user theme.

For now, the AELF android app is missing support for these icons:

![Screenshot_20230601-155209](https://github.com/HackMyChurch/aelf-dailyreadings/assets/72463129/ccec4038-3fac-4fd7-b170-b00f3119e6eb)

**Comment by nathanael-h** [comment]
Actually I'm focused on the iOS app, that should be one day the Android app also...

But this icon studd might not be a big change. I could try to add this if @yadutaf would agree.
--
Nathanaël
decouvrir-dieu.com
isidorus.fr Cloud dégooglisé pour la famille et les amis

1 juin 2023 15:54:13 ascpial ***@***.***>:

**Comment by yadutaf** [comment]
I gave it a try locally, here is a preview:

![image](https://github.com/HackMyChurch/aelf-dailyreadings/assets/739985/138f065c-4b80-4bc0-9cb1-873d22138e99)

**Comment by nathanael-h** [comment]
Cool :+1:

**Comment by yadutaf** [comment]
Just sent 2.8.0 to beta channel, with this fix. Closing.
