### ISSUE TITLE
The Liturgy of the Hours is not in sync with the website


### ISSUE THREAD

**Issue by ascpial** [HackMyChurch/aelf-dailyreadings#49]
![Screenshot_20240809-182815.png](https://github.com/user-attachments/assets/b0ee8f27-a662-43cd-bc55-fde7361412a0)

![Screenshot_20240809-182806.png](https://github.com/user-attachments/assets/e7737ac3-88df-4835-912d-ee641861d7c3)

**Comment by yadutaf** [comment]
Hi !

The difference you were experiencing is related to the "zone". The application is configured for the local zone by default (france in this case) while the website displays the "romain" region by default.

If you switch the website to the french zone, the text are the same: https://www.aelf.org/2024-08-09/france/vepres.
