### ISSUE TITLE
Text bug, messe,refrain évangile

### ISSUE THREAD

**Issue by nathanael-h** [HackMyChurch/aelf-dailyreadings#5]
Hello,

Today I saw a bug in the text before the gospel of today's mass. I'll join a screenshot.

**Comment by yadutaf** [comment]
@nath5394 Désolé, je n'ai pas vu ton rapport d'erreur. Il doit y avoir un soucis de CSS du coté de https://github.com/HackMyChurch/aelf-dailyreadings/blob/master/app/src/main/java/co/epitre/aelf_lectures/LectureFragment.java#L200. Je garde l'issue sous le coude, ce morceau a grand besoin d'être mis au propre. Si quelque chose te saute aux yeux dans cette CSS, n'hésite pas ;)

**Comment by nath5394** [comment]
@randolphgamo Salut, c'est super sympa ! Si tu veux on peut avancer ensemble sur l'ajout de la Bible. Regarde la branche jt-bible sur mon fork. Ça avance bien !
