### ISSUE TITLE
Je souhaite participer à ce projet

### ISSUE THREAD

**Issue by randolphgamo** [HackMyChurch/aelf-dailyreadings#6]
Hello, bjr.
Je souhaite participer à ce projet.
Comment puis je vous être utile?
Je suis un développeur mais plus orienté vers administration système sous linux cependant j'ai un esprit ouvert et j'ai surtout là volonté d'apporter une modeste contribution

**Comment by yadutaf** [comment]
Bonjour @randolphgamo,

Merci pour ta proposition ! Coté administration système Linux, il n'y a pas grand chose à faire, il y a 3 VPS, bien surveillés par Ansible/Docker, ça tourne à peu près tout seul :wink: 

Cela dit, j'ai de nombreux rapports d'erreurs de connexion depuis l'Afrique, sans avoir vu de points communs particuliers de pays ou de fournisseur d'accès. Si tes connaissances en administration systèmes pouvaient m'aiguiller dans la résolution, ce serait top !

Si tu veux en parler, n'hésite pas à me contacter par mail (dans l'application).

Bonne journée,

**Comment by randolphgamo** [comment]
Salut @yudataf. Ce sujet m'intéresse
