### ISSUE TITLE
f-droid

### ISSUE THREAD

**Issue by Arnaudv6** [HackMyChurch/aelf-dailyreadings#8]
Bonjour et merci beaucoup pour cette appli !
Je suis en veille permanente, et j'étais un peu vexé que mon petit frère séminariste me présente l'appli.
Je n'avais pas pensé à chercher une appli AELF..... Et surtout mes applis viennent (presque) toutes de [fdroid](https://f-droid.org/fr/)...
"Elle est bien ton appli frérot, dommage qu'elle soit pas open-source".

Donc je découvre avec joie que j'avais tort : la mettriez-vous dans fdroid ? Pour toucher plus de geeks =D
Je ne peux pas vous guider la dessus : je ne l'ai jamais fait.

J'ai des __*notions*__ de python pour un éventuel, coup de patte au server. A dire rapidement.

**Comment by AMDG2** [comment]
Bonjour @Arnaudv6 
C'est effectivement une amélioration souhaitable et qui devrait être possible, je ne crois pas que l'appli enfreigne des règles de f-droid.

@yadutaf Est-ce que tu vois un inconvénient à ce que je lance la procédure pour intégrer l'application dans f-droid ?

**Comment by yadutaf** [comment]
Non, au contraire. C'est une excellente idée ! Cela fait partie de la longue des choses que j'aurais aimé faire. Grande joie que vous preniez le sujet.

@Arnaudv6 Désolé de n'avoir pas répondu à votre proposition. Je suis complètement sous l'eau pour (d'heureuses) raisons personnelles :)

@AMDG2 Veux-tu que l'on programme un appel skype / whatsapp pour lancer cela et surtout vous donner + d'autonomie sur le projet ?

**Comment by AMDG2** [comment]
Je t’envoie un mail pour en discuter.

**Comment by nath5394** [comment]
Je m'y mets doucement. 
Il n'y a pas encore de commit. Ça va venir. 
https://gitlab.com/nathanael2/fdroiddata 
Tu veux les droits dessus ?

**Comment by AMDG2** [comment]
L'application est maintenant disponible sur f-droid !

**Comment by Arnaudv6** [comment]
Super !!!
Merci beaucoup, ça marche bien, et j'imagine que ça va évangéliser à bloc :-)
